#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	startTask(encoderTask);

	leftEncoderCount = 0;


	while(leftEncoderCount < 75)
	{
		motor[motorB] = 50;
		motor[motorC] = 50;
	}

}
