#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//Move forward in a straight line
motor[motorB] = 50;
motor[motorC] = 50;
wait1Msec(3000);

//Turn 90 degrees right
motor[motorB] = 50;
motor[motorC] = 0;
wait1Msec(680);
motor[motorB] = 50;
motor[motorC] = 50;
wait1Msec(3000);
 motor[motorB] = 50; motor[motorC] = 0; wait1Msec(680);  motor[motorB] = 50; motor[motorC] = 50; wait1Msec(3000);  motor[motorB] = 50; motor[motorC] = 0; wait1Msec(680);  motor[motorB] = 50; motor[motorC] = 50; wait1Msec(3000);  motor[motorB] = 50; motor[motorC] = 0; wait1Msec(680);}

}
