#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Straight line
	setMotorSyncTime(left, right, 0, 2500, 50);
	sleep(2500);

	//Straight line
	setMotorSyncTime(left, right, 0, 2600, 50);
	sleep(2600);

	//Straight line
	setMotorSyncTime(left, right, 0, 2250, 50);
	sleep(2250);

	//Straight line
	setMotorSyncTime(left, right, 0, 2600, 50);
	sleep(2600);

}
