#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     light,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	//Variables for speed and battery
 	int currentSpeed;
	float batteryLife = getBatteryVoltage();


	motor[motorB] = 50;
	motor[motorC] = 50;

	//Set the variable to the speed of the wheels
	currentSpeed = getMotorSpeed(motorB);

	//Displays Battery and Speed
	displayCenteredBigTextLine(3, "%f", batteryLife);
	displayCenteredBigTextLine(6, "%d", currentSpeed);

	sleep(10000);


}
