#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Initialise touch sensor
const tSensors touchSensor = (tSensors) S1;

//Initialise sonar sensor
const tSensors sonarSensor = (tSensors) S4;

task main()
{

	//Go Forward until touch
		while(SensorValue(touchSensor) ==0)
		{
			motor[motorB] = 50;
			motor[motorC] = 50;
		}

		setMotorSyncTime(left, right, 0, 500, -25);
		sleep(500);
		//2nd Left hand turn
		setMotorSyncTime(left, right, -100, 710, 25);
		sleep(710);



	//Go Forward until within 10 cm of obstacle
	while(SensorValue(sonarSensor) > 10)
	{
		motor[motorB] = 50;
		motor[motorC] = 50;
	}
		setMotorSyncTime(left, right, 0, 250, -25);
		sleep(250);
		//1st Left hand turn
		setMotorSyncTime(left, right, -100, 710, 25);
		sleep(710);






		//Go Forward until within 10 cm of obstacle
	while(SensorValue(sonarSensor) > 10)
	{
		motor[motorB] = 50;
		motor[motorC] = 50;
	}
		setMotorSyncTime(left, right, 0, 250, -25);
		sleep(250);
		//1st Left hand turn
		setMotorSyncTime(left, right, -100, 710, 25);
		sleep(710);

		resetMotorEncoder(motorB);
		resetMotorEncoder(motorC);
		setMotorTarget(motorB, 1000, 50);
		setMotorTarget(motorC, 1000, 50);
		repeatUntil(getMotorEncoder(motorB) == getMotorTarget(motorB));
		repeatUntil(getMotorEncoder(motorC) == getMotorTarget(motorC));
}
