#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int i;

	i = rand() % 3;


if(i==0)
{
	//1st Straight line
	setMotorSyncTime(left, right, 0, 2500, 50);
	sleep(2500);

	//1st Left hand turn
	setMotorSyncTime(left, right, -100, 710, 25);
	sleep(710);

	//2nd Straight line
	setMotorSyncTime(left, right, 0, 2400, 50);
	sleep(2400);

	//2nd Left hand turn
	setMotorSyncTime(left, right, -100, 705, 25);
	sleep(705);

	//3rd Straight line
	setMotorSyncTime(left, right, 0, 2500, 50);
	sleep(2500);

	//3rd Left hand turn
	setMotorSyncTime(left, right, -100, 705, 25);
	sleep(705);

	//4th Straight
	setMotorSyncTime(left, right, 0, 1100, 50);
	sleep(1100);

}
if(i==1)
{
	//1st Straight line
	setMotorSyncTime(left, right, 0, 10000, 25);
	sleep(5000);

	//1st Left hand turn
	setMotorSyncTime(left, right, -100, 2840, 12.5);
	sleep(1350);

	//2nd Straight line
	setMotorSyncTime(left, right, 0, 9600, 25);
	sleep(4800);

	//2nd Left hand turn
	setMotorSyncTime(left, right, -100, 2420, 12.5);
	sleep(1350);

	//3rd Straight line
	setMotorSyncTime(left, right, 0, 10000, 25);
	sleep(5000);

	//3rd Left hand turn
	setMotorSyncTime(left, right, -100, 2820, 12.5);
	sleep(1350);

	//4th Straight
	setMotorSyncTime(left, right, 0, 4400, 25);
	sleep(2200);
}
if(i==2)
{
	//1st Straight line
	setMotorSyncTime(left, right, 0, 2500, 100);
	sleep(1800);

	//Short pause
	setMotorSyncTime(left, right, 0, 200, 0);
	sleep(200);
	//1st Left hand turn
	setMotorSyncTime(left, right, -100, 710, 50);
	sleep(355);

	//2nd Straight line
	setMotorSyncTime(left, right, 0, 2400, 100);
	sleep(1800);

	//Short pause
	setMotorSyncTime(left, right, 0, 200, 0);
	sleep(200);
	//2nd Left hand turn
	setMotorSyncTime(left, right, -100, 705, 50);
	sleep(355);

	//3rd Straight line
	setMotorSyncTime(left, right, 0, 2500, 100);
	sleep(1875);

	//Short pause
	setMotorSyncTime(left, right, 0, 200, 0);
	sleep(200);
	//3rd Left hand turn
	setMotorSyncTime(left, right, -100, 705, 50);
	sleep(355);

	//4th Straight
	setMotorSyncTime(left, right, 0, 1100, 100);
	sleep(733);
}
}
