#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     light,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Initialise sonar sensor
const tSensors sonarSensor = (tSensors) S4;

task main()
{

	//Go Forward until within 10 cm of obstacle
	while(SensorValue(sonarSensor) > 10)
	{
		motor[motorB] = 50;
		motor[motorC] = 50;
	}
		motor[motorB] = -50;
		motor[motorC] = -50;
		sleep(1000);


}
