#pragma config(Sensor, S1,     left,           sensorEV3_Touch)
#pragma config(Sensor, S4,     right,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Initialise touch sensor
const tSensors touchSensor = (tSensors) S1;


task main()
{

	//Go Forward until touch
	while(SensorValue(touchSensor) ==0)
	{
		motor[motorB] = 50;
		motor[motorC] = 50;
	}

		//Reverse for 1 sec
		motor[motorB] = -50;
		motor[motorC] = -50;
		sleep(1000);
}
