#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//1st Straight line
	setMotorSyncTime(left, right, 0, 2500, 100);
	sleep(1800);

	setMotorSyncTime(left, right, 0, 200, 0);
	sleep(200);
	//1st Left hand turn
	setMotorSyncTime(left, right, -100, 710, 50);
	sleep(355);

	//2nd Straight line
	setMotorSyncTime(left, right, 0, 2400, 100);
	sleep(1800);

	setMotorSyncTime(left, right, 0, 200, 0);
	sleep(200);
	//2nd Left hand turn
	setMotorSyncTime(left, right, -100, 705, 50);
	sleep(355);

	//3rd Straight line
	setMotorSyncTime(left, right, 0, 2500, 100);
	sleep(1875);

	setMotorSyncTime(left, right, 0, 200, 0);
	sleep(200);
	//3rd Left hand turn
	setMotorSyncTime(left, right, -100, 705, 50);
	sleep(355);

	//4th Straight
	setMotorSyncTime(left, right, 0, 1100, 100);
	sleep(733);

}
