#pragma config(Sensor, S1,     left,           sensorEV3_Touch)
#pragma config(Sensor, S4,     right,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
	setMotorTarget(motorB, 1000, 50);
	setMotorTarget(motorC, 1000, 50);
	repeatUntil(getMotorEncoder(motorB) == getMotorTarget(motorB));
	repeatUntil(getMotorEncoder(motorC) == getMotorTarget(motorC));





}
