#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     light,          sensorEV3_Color)
#pragma config(Sensor, S4,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//initialise light sensor
const tSensors lightSensor =  (tSensors) S2;

//Initialise touch sensor
const tSensors touchSensor = (tSensors) S1;

//Initialise sonar sensor
const tSensors sonarSensor = (tSensors) S4;

task main()
{

	while(1==1)
	{

		while(SensorValue(sonarSensor) > 10)
			{
				if(SensorValue(lightSensor) < 50)
				{
					motor[motorB] = 40;
					motor[motorC] = 0;
				}


				else
				{
					motor[motorB] = 0;
					motor[motorC] = 40;
				}
			}

		setMotorSyncTime(left, right, 100, 750, 25);
		sleep(750);
		setMotorSyncTime(left, right, 0, 150, 25);
		sleep(150);
		while(SensorValue(lightSensor) > 50)
		{
			motor[motorB] = 20;
			motor[motorC] = 40;
		}


	}


}
