#pragma config(Sensor, S2,     light,          sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const tSensors lightSensor =  (tSensors) S2;


task main()
{
	while(SensorValue(lightSensor) > 50)
	{
		motor[motorB] = 50;
		motor[motorC] = 50;
	}

	motor[motorB] = -50;
	motor[motorC] = -50;
	wait1Msec(1000);

}
