#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     light,          sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//initialise light sensor
const tSensors lightSensor =  (tSensors) S2;

//Initialise touch sensor
const tSensors touchSensor = (tSensors) S1;


task main()
{

	//Go Forward until touch
	while(SensorValue(touchSensor) ==0)
	{

			if(SensorValue(lightSensor) < 50)
			{
				motor[motorB] = 40;
				motor[motorC] = 0;
			}

			else
			{
				motor[motorB] = 0;
				motor[motorC] = 40;
			}
		}

		motor[motorB] = 0;
		motor[motorC] = 0;
		sleep(1000);
}
