#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//1st Straight line
	setMotorSyncTime(left, right, 0, 2500, 50);
	sleep(2500);

	//1st Left hand turn
	setMotorSyncTime(left, right, -100, 720, 25);
	sleep(720);

	//2nd Straight line
	setMotorSyncTime(left, right, 0, 2250, 50);
	sleep(2250);

	//2nd Left hand turn
	setMotorSyncTime(left, right, -100, 720, 25);
	sleep(720);

	//3rd Straight line
	setMotorSyncTime(left, right, 0, 2500, 50);
	sleep(2500);

	//3rd Left hand turn
	setMotorSyncTime(left, right, -100, 720, 25);
	sleep(720);

	//4th Straight
	setMotorSyncTime(left, right, 0, 1100, 50);
	sleep(1100);

	//4th Left hand turn
	setMotorSyncTime(left, right, -100, 710, 25);
	sleep(710);

	//5th Straight
	setMotorSyncTime(left, right, 0, 800, 50);
	sleep(800);


}
