#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//1st Straight line
	setMotorSyncTime(left, right, 0, 2500, 50);
	sleep(2500);

	//1st Left hand turn
	setMotorSyncTime(left, right, -100, 720, 25);
	sleep(720);

	//2nd Straight line
	setMotorSyncTime(left, right, 0, 2250, 50);
	sleep(2250);

	//1st Right hand turn
	setMotorSyncTime(left, right, 100, 720, 25);
	sleep(720);

	//3rd Straight
	setMotorSyncTime(left, right, 0, 1000, 50);
	sleep(1000);

	//2nd Right hand turn
	setMotorSyncTime(left, right, 100, 720, 25);
	sleep(720);

	//4th Straight
	setMotorSyncTime(left, right, 0, 1000, 50);
	sleep(1000);

	//180
	setMotorSyncTime(left, right, 100, 1375, 25);
	sleep(1375);

	//5th Straight
	setMotorSyncTime(left, right, 0, 1100, 50);
	sleep(1100);

	//2nd Left hand turn
	setMotorSyncTime(left, right, -100, 720, 25);
	sleep(720);

	//6th Straight line
	setMotorSyncTime(left, right, 0, 3500, 50);
	sleep(3500);

	//3rd Left hand turn
	setMotorSyncTime(left, right, -100, 710, 25);
	sleep(710);

	//7th Straight
	setMotorSyncTime(left, right, 0, 1100, 50);
	sleep(1100);

	//4th Left hand turn
	setMotorSyncTime(left, right, -100, 710, 25);
	sleep(710);

	//8th Straight
	setMotorSyncTime(left, right, 0, 800, 50);
	sleep(800);

}
