#pragma config(Sensor, S2,     light,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//initialise light sensor
const tSensors colorSensor =  (tSensors) S2;

//Initialise sonar sensor
const tSensors sonarSensor = (tSensors) S4;

void begin(void);

void row(void);

void turnl(void);

void turnr(void);

int whitesqr, blacksqr = 0;
int i = 0;

task main()
{


	int count = 0;


	begin();

	row();
	turnl();
	row();
	turnr();
	row();
	turnl();
	row();
	turnr();
	row();
	turnl();
	row();
	turnr();
	row();



}


void begin(void)
{
	while((getColorName(colorSensor) == colorWhite)||(getColorName(colorSensor) == colorBlack))
	{
		resetMotorEncoder(motorB);
		resetMotorEncoder(motorC);
		setMotorTarget(motorB, 320, 30);
		setMotorTarget(motorC, 320, 30);
		repeatUntil(getMotorEncoder(motorB) == getMotorTarget(motorB));
		repeatUntil(getMotorEncoder(motorC) == getMotorTarget(motorC));
	}

	setMotorSyncTime(left, right, 0, 1000, -25);
	sleep(1000);
	setMotorSyncTime(left, right, 100, 710, -25);
	sleep(710);
	setMotorSyncTime(left, right, 0, 400, -20);
	sleep(400);
}

void row(void)
{
	for(i=0;i<9;i++)
	{
		if(getColorName(colorSensor) == colorBlack)
		{
			blacksqr++;
			displayCenteredBigTextLine(3, "%d", blacksqr);
		}
		if(getColorName(colorSensor) == colorWhite)
		{
			whitesqr++;
			displayCenteredBigTextLine(6, "%d", whitesqr);
		}
		resetMotorEncoder(motorB);
		resetMotorEncoder(motorC);
		setMotorTarget(motorB, 320, 30);
		setMotorTarget(motorC, 320, 30);
		repeatUntil(getMotorEncoder(motorB) == getMotorTarget(motorB));
		repeatUntil(getMotorEncoder(motorC) == getMotorTarget(motorC));
	}

}

void turnl(void)
{
	if(getColorName(colorSensor) == colorBlack)
	{
		blacksqr++;
		displayCenteredBigTextLine(3, "%d", blacksqr);
	}
	if(getColorName(colorSensor) == colorWhite)
	{
		whitesqr++;
		displayCenteredBigTextLine(6, "%d", whitesqr);
	}

	setMotorSyncTime(left, right, 100, 720, -25);
	sleep(720);

	setMotorSyncTime(left, right, 0, 1175, 25);
	sleep(1100);

	setMotorSyncTime(left, right, 100, 720, -25);
	sleep(720);

	setMotorSyncTime(left, right, 0, 600, -25);
	sleep(600);
}

void turnr(void)
{
	setMotorSyncTime(left, right, -100, 720, -25);
	sleep(720);

	setMotorSyncTime(left, right, 0, 1175, 25);
	sleep(1100);

	setMotorSyncTime(left, right, -100, 720, -25);
	sleep(720);

	setMotorSyncTime(left, right, 0, 600, -25);
	sleep(600);
}
