#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     light,          sensorEV3_Color)
#pragma config(Sensor, S3,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//initialise light sensor
const tSensors lightSensor =  (tSensors) S2;

//Initialise touch sensor
const tSensors touchSensor = (tSensors) S1;

//Initialise sonar sensor
const tSensors sonarSensor = (tSensors) S4;

//Initialise gyro sensor
const tSensors gyroSensor = (tSensors) S3;


void begin(void);


task main()
{
	int i;

	int lines;

	begin();

	while(SensorValue(lightSensor) <= 60)
	{
		//Display total lines crossed
		displayCenteredBigTextLine(3, "%d", lines);

		resetMotorEncoder(motorB);
		resetMotorEncoder(motorC);
		setMotorTarget(motorB, 328, 50);
		setMotorTarget(motorC, 328, 50);
		repeatUntil(getMotorEncoder(motorB) == getMotorTarget(motorB));
		repeatUntil(getMotorEncoder(motorC) == getMotorTarget(motorC));

	}

	lines = lines+1;

	while(SensorValue(lightSensor) > 60)
	{
		//Display total lines crossed
		displayCenteredBigTextLine(3, "%d", lines);

		resetMotorEncoder(motorB);
		resetMotorEncoder(motorC);
		setMotorTarget(motorB, 328, 50);
		setMotorTarget(motorC, 328, 50);
		repeatUntil(getMotorEncoder(motorB) == getMotorTarget(motorB));
		repeatUntil(getMotorEncoder(motorC) == getMotorTarget(motorC));

	}

}


void begin(void)
{
	//Go straight to the corner
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
	setMotorTarget(motorB, 984, 50);
	setMotorTarget(motorC, 984, 50);
	repeatUntil(getMotorEncoder(motorB) == getMotorTarget(motorB));
	repeatUntil(getMotorEncoder(motorC) == getMotorTarget(motorC));

	//Turn left
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
	setMotorTarget(motorB, -175, 30);
	setMotorTarget(motorC, 175, 30);
	repeatUntil(getMotorEncoder(motorB) == getMotorTarget(motorB));
	repeatUntil(getMotorEncoder(motorC) == getMotorTarget(motorC));

}
