#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int random;
	int speed;
	int time;


	random = rand() % 4;

	if(random == 0)
	{
		speed = 25;
		time = .5


	setMotorSyncTime(left, right, 0, 3000, speed);
	sleep(8000);


}
